import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/layout/Header";
import { Providers } from "@/src/providers/providers";
import ChatBot from "@/src/components/common/Chatbot/ChatBot";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`}>
        <Providers>
          <Header />
          {children}
          <ChatBot />
        </Providers>
      </body>
    </html>
  );
}
